name: Automated Data Preprocessing

on:
  push:
    branches: [main]
    paths:
      - "Crop_recommendation.csv"
      - "preprocessing/automate_Muh-Iqbal-H.py"
  pull_request:
    branches: [main]
    paths:
      - "Crop_recommendation.csv"
      - "preprocessing/automate_Muh-Iqbal-H.py"

jobs:
  preprocess-data:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.10"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn numpy

      - name: Run preprocessing script
        run: |
          cd preprocessing
          python automate_Muh_Iqbal_Hardiyanto.py \
            --input ../Crop_recommendation.csv \
            --output_dir Crop_recommendation_processed

      - name: Commit processed data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add preprocessing/Crop_recommendation_processed/*
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-commit processed data [skip ci]"
          git push

      - name: Upload processed data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: preprocessing/Crop_recommendation_processed/
          retention-days: 8
